title: Cosmic Deflation Docs
description: essential documentation of all the services related to the cosmic deflation
theme: just-the-docs

url: https://cosmic-deflation.github.io/doc

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
